# Site settings
title: Developing is the most fun in the world!
email: gabycho41@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  : 심희수의 깃 블로그
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://CHeessoo.github.io" # the base hostname & protocol for your site
github_username:  CHeessoo

# Build settings
markdown: kramdown
